### ISSUE TITLE
MetalLB instructions need updates 

### ISSUE THREAD

**Issue by LincolnBryant** [slateci/slateci.github.io#105]
Installing a fresh cluster today with MetalLB v0.10.2 as per the instructions, I ran into a problem that required me to do the following:

```
kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
```

I am not sure if this is a new, general problem with MetalLB, or a problem between keyboard and chair.

Perhaps we should update the instructions for MetalLB v0.11.0, as is recommended by upstream? https://metallb.universe.tf/installation/

It may obviate this issue.

**Comment by adamhgriffith-uofu** [comment]
Jason has applied these changes to the site.
